import Head from "next/head";

interface HeaderAreaProps {
  title?: string;
  description?: string;
}

const HeadArea = ({ title, description }: HeaderAreaProps): JSX.Element => (
  <Head>
    <title>{title || "Area do Aluno Redesign"}</title>
    <meta name="description" content={description || "Generated by sdpm cli"} />
    <meta name="keywords" content="React, Next.js, TypeScript" />
    <meta name="author" content="Rian Oliveira" />
    <meta name="theme-color" content="#e9ae30" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);
export default HeadArea;
